# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LoadMoreExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LoadMoreExample
  pod 'Alamofire'
  pod 'AZRemoteTable'
  pod 'AZImagePreview'
  pod 'AZEmptyState'
  pod 'SwiftyJSON'
  pod 'Kingfisher'

end
